// Code generated by protoc-gen-go. DO NOT EDIT.
// source: channel.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NetworkMessage_Type int32

const (
	NetworkMessage_BOOTSTRAP_REQUEST  NetworkMessage_Type = 0
	NetworkMessage_BOOTSTRAP_RESPONSE NetworkMessage_Type = 1
)

var NetworkMessage_Type_name = map[int32]string{
	0: "BOOTSTRAP_REQUEST",
	1: "BOOTSTRAP_RESPONSE",
}

var NetworkMessage_Type_value = map[string]int32{
	"BOOTSTRAP_REQUEST":  0,
	"BOOTSTRAP_RESPONSE": 1,
}

func (x NetworkMessage_Type) String() string {
	return proto.EnumName(NetworkMessage_Type_name, int32(x))
}

func (NetworkMessage_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c8f385724121f37b, []int{1, 0}
}

type ChannelMessage struct {
	Cid                  []byte               `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	Message              string               `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Topic                string               `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`
	PeerID               string               `protobuf:"bytes,4,opt,name=peerID,proto3" json:"peerID,omitempty"`
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Signature            []byte               `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ChannelMessage) Reset()         { *m = ChannelMessage{} }
func (m *ChannelMessage) String() string { return proto.CompactTextString(m) }
func (*ChannelMessage) ProtoMessage()    {}
func (*ChannelMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8f385724121f37b, []int{0}
}

func (m *ChannelMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChannelMessage.Unmarshal(m, b)
}
func (m *ChannelMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChannelMessage.Marshal(b, m, deterministic)
}
func (m *ChannelMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChannelMessage.Merge(m, src)
}
func (m *ChannelMessage) XXX_Size() int {
	return xxx_messageInfo_ChannelMessage.Size(m)
}
func (m *ChannelMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ChannelMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ChannelMessage proto.InternalMessageInfo

func (m *ChannelMessage) GetCid() []byte {
	if m != nil {
		return m.Cid
	}
	return nil
}

func (m *ChannelMessage) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ChannelMessage) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *ChannelMessage) GetPeerID() string {
	if m != nil {
		return m.PeerID
	}
	return ""
}

func (m *ChannelMessage) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *ChannelMessage) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type NetworkMessage struct {
	Type NetworkMessage_Type `protobuf:"varint,1,opt,name=type,proto3,enum=NetworkMessage_Type" json:"type,omitempty"`
	// Types that are valid to be assigned to Payload:
	//	*NetworkMessage_Request
	//	*NetworkMessage_Response
	Payload              isNetworkMessage_Payload `protobuf_oneof:"payload"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *NetworkMessage) Reset()         { *m = NetworkMessage{} }
func (m *NetworkMessage) String() string { return proto.CompactTextString(m) }
func (*NetworkMessage) ProtoMessage()    {}
func (*NetworkMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8f385724121f37b, []int{1}
}

func (m *NetworkMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetworkMessage.Unmarshal(m, b)
}
func (m *NetworkMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetworkMessage.Marshal(b, m, deterministic)
}
func (m *NetworkMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkMessage.Merge(m, src)
}
func (m *NetworkMessage) XXX_Size() int {
	return xxx_messageInfo_NetworkMessage.Size(m)
}
func (m *NetworkMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkMessage.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkMessage proto.InternalMessageInfo

func (m *NetworkMessage) GetType() NetworkMessage_Type {
	if m != nil {
		return m.Type
	}
	return NetworkMessage_BOOTSTRAP_REQUEST
}

type isNetworkMessage_Payload interface {
	isNetworkMessage_Payload()
}

type NetworkMessage_Request struct {
	Request *NetworkMessage_BootstrapRequest `protobuf:"bytes,2,opt,name=request,proto3,oneof"`
}

type NetworkMessage_Response struct {
	Response *NetworkMessage_BootstrapResponse `protobuf:"bytes,3,opt,name=response,proto3,oneof"`
}

func (*NetworkMessage_Request) isNetworkMessage_Payload() {}

func (*NetworkMessage_Response) isNetworkMessage_Payload() {}

func (m *NetworkMessage) GetPayload() isNetworkMessage_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *NetworkMessage) GetRequest() *NetworkMessage_BootstrapRequest {
	if x, ok := m.GetPayload().(*NetworkMessage_Request); ok {
		return x.Request
	}
	return nil
}

func (m *NetworkMessage) GetResponse() *NetworkMessage_BootstrapResponse {
	if x, ok := m.GetPayload().(*NetworkMessage_Response); ok {
		return x.Response
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*NetworkMessage) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*NetworkMessage_Request)(nil),
		(*NetworkMessage_Response)(nil),
	}
}

type NetworkMessage_BootstrapRequest struct {
	Topic                string   `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NetworkMessage_BootstrapRequest) Reset()         { *m = NetworkMessage_BootstrapRequest{} }
func (m *NetworkMessage_BootstrapRequest) String() string { return proto.CompactTextString(m) }
func (*NetworkMessage_BootstrapRequest) ProtoMessage()    {}
func (*NetworkMessage_BootstrapRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8f385724121f37b, []int{1, 0}
}

func (m *NetworkMessage_BootstrapRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetworkMessage_BootstrapRequest.Unmarshal(m, b)
}
func (m *NetworkMessage_BootstrapRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetworkMessage_BootstrapRequest.Marshal(b, m, deterministic)
}
func (m *NetworkMessage_BootstrapRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkMessage_BootstrapRequest.Merge(m, src)
}
func (m *NetworkMessage_BootstrapRequest) XXX_Size() int {
	return xxx_messageInfo_NetworkMessage_BootstrapRequest.Size(m)
}
func (m *NetworkMessage_BootstrapRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkMessage_BootstrapRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkMessage_BootstrapRequest proto.InternalMessageInfo

func (m *NetworkMessage_BootstrapRequest) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

type NetworkMessage_BootstrapResponse struct {
	Topic                string   `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Cids                 [][]byte `protobuf:"bytes,2,rep,name=cids,proto3" json:"cids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NetworkMessage_BootstrapResponse) Reset()         { *m = NetworkMessage_BootstrapResponse{} }
func (m *NetworkMessage_BootstrapResponse) String() string { return proto.CompactTextString(m) }
func (*NetworkMessage_BootstrapResponse) ProtoMessage()    {}
func (*NetworkMessage_BootstrapResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8f385724121f37b, []int{1, 1}
}

func (m *NetworkMessage_BootstrapResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetworkMessage_BootstrapResponse.Unmarshal(m, b)
}
func (m *NetworkMessage_BootstrapResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetworkMessage_BootstrapResponse.Marshal(b, m, deterministic)
}
func (m *NetworkMessage_BootstrapResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkMessage_BootstrapResponse.Merge(m, src)
}
func (m *NetworkMessage_BootstrapResponse) XXX_Size() int {
	return xxx_messageInfo_NetworkMessage_BootstrapResponse.Size(m)
}
func (m *NetworkMessage_BootstrapResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkMessage_BootstrapResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkMessage_BootstrapResponse proto.InternalMessageInfo

func (m *NetworkMessage_BootstrapResponse) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *NetworkMessage_BootstrapResponse) GetCids() [][]byte {
	if m != nil {
		return m.Cids
	}
	return nil
}

func init() {
	proto.RegisterEnum("NetworkMessage_Type", NetworkMessage_Type_name, NetworkMessage_Type_value)
	proto.RegisterType((*ChannelMessage)(nil), "ChannelMessage")
	proto.RegisterType((*NetworkMessage)(nil), "NetworkMessage")
	proto.RegisterType((*NetworkMessage_BootstrapRequest)(nil), "NetworkMessage.BootstrapRequest")
	proto.RegisterType((*NetworkMessage_BootstrapResponse)(nil), "NetworkMessage.BootstrapResponse")
}

func init() { proto.RegisterFile("channel.proto", fileDescriptor_c8f385724121f37b) }

var fileDescriptor_c8f385724121f37b = []byte{
	// 376 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0x41, 0x6f, 0xda, 0x30,
	0x1c, 0xc5, 0x49, 0x08, 0xb0, 0xfc, 0x61, 0x28, 0x58, 0x0c, 0x59, 0xd1, 0xa4, 0x65, 0x9c, 0x72,
	0x0a, 0x52, 0xa6, 0x49, 0x3b, 0x6c, 0x9a, 0x96, 0x0d, 0x89, 0x1d, 0x0a, 0xd4, 0x49, 0x2f, 0xbd,
	0x54, 0x21, 0xb8, 0x69, 0x54, 0x88, 0xdd, 0xd8, 0xa8, 0xe2, 0xeb, 0xf5, 0xb3, 0xf4, 0x83, 0x54,
	0x38, 0x0d, 0x50, 0x5a, 0xf5, 0xe6, 0xf7, 0xfc, 0x7b, 0xce, 0xff, 0xfd, 0x03, 0x1f, 0x93, 0x9b,
	0x38, 0xcf, 0xe9, 0xca, 0xe3, 0x05, 0x93, 0xcc, 0xfe, 0x92, 0x32, 0x96, 0xae, 0xe8, 0x48, 0xa9,
	0xc5, 0xe6, 0x7a, 0x24, 0xb3, 0x35, 0x15, 0x32, 0x5e, 0xf3, 0x12, 0x18, 0x3e, 0x68, 0xd0, 0xfd,
	0x5b, 0x46, 0xce, 0xa8, 0x10, 0x71, 0x4a, 0x91, 0x05, 0xf5, 0x24, 0x5b, 0x62, 0xcd, 0xd1, 0xdc,
	0x0e, 0xd9, 0x1d, 0x11, 0x86, 0xd6, 0xba, 0xbc, 0xc4, 0xba, 0xa3, 0xb9, 0x26, 0xa9, 0x24, 0xea,
	0x43, 0x43, 0x32, 0x9e, 0x25, 0xb8, 0xae, 0xfc, 0x52, 0xa0, 0x01, 0x34, 0x39, 0xa5, 0xc5, 0xff,
	0x7f, 0xd8, 0x50, 0xf6, 0xb3, 0x42, 0x3f, 0xc0, 0xdc, 0x7f, 0x1f, 0x37, 0x1c, 0xcd, 0x6d, 0xfb,
	0xb6, 0x57, 0x4e, 0xe8, 0x55, 0x13, 0x7a, 0x51, 0x45, 0x90, 0x03, 0x8c, 0x3e, 0x83, 0x29, 0xb2,
	0x34, 0x8f, 0xe5, 0xa6, 0xa0, 0xb8, 0xa9, 0x26, 0x3b, 0x18, 0xc3, 0x47, 0x1d, 0xba, 0x53, 0x2a,
	0xef, 0x59, 0x71, 0x5b, 0x95, 0x70, 0xc1, 0x90, 0x5b, 0x4e, 0x55, 0x8b, 0xae, 0xdf, 0xf7, 0x5e,
	0x5e, 0x7b, 0xd1, 0x96, 0x53, 0xa2, 0x08, 0xf4, 0x13, 0x5a, 0x05, 0xbd, 0xdb, 0x50, 0x21, 0x55,
	0xb9, 0xb6, 0xef, 0x9c, 0xc2, 0x01, 0x63, 0x52, 0xc8, 0x22, 0xe6, 0xa4, 0xe4, 0x26, 0x35, 0x52,
	0x45, 0xd0, 0x6f, 0xf8, 0x50, 0x50, 0xc1, 0x59, 0x2e, 0xa8, 0xda, 0x41, 0xdb, 0xff, 0xfa, 0x4e,
	0xbc, 0x04, 0x27, 0x35, 0xb2, 0x0f, 0xd9, 0x2e, 0x58, 0xa7, 0xef, 0x1f, 0xb6, 0xaa, 0x1d, 0x6d,
	0xd5, 0xfe, 0x05, 0xbd, 0x57, 0x4f, 0xbd, 0x8d, 0x22, 0x04, 0x46, 0x92, 0x2d, 0x05, 0xd6, 0x9d,
	0xba, 0xdb, 0x21, 0xea, 0x3c, 0xfc, 0x0e, 0xc6, 0xae, 0x35, 0xfa, 0x04, 0xbd, 0x60, 0x36, 0x8b,
	0xc2, 0x88, 0xfc, 0x99, 0x5f, 0x91, 0xf1, 0xf9, 0xc5, 0x38, 0x8c, 0xac, 0x1a, 0x1a, 0x00, 0x3a,
	0xb6, 0xc3, 0xf9, 0x6c, 0x1a, 0x8e, 0x2d, 0x2d, 0x30, 0xa1, 0xc5, 0xe3, 0xed, 0x8a, 0xc5, 0xcb,
	0xc0, 0xb8, 0xd4, 0xf9, 0x62, 0xd1, 0x54, 0x7f, 0xea, 0xdb, 0x53, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x8f, 0x1a, 0x31, 0xfa, 0x6a, 0x02, 0x00, 0x00,
}
